version: 2
jobs:
  build:
    docker:
      - image: regviz/node-xcb
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

    working_directory: ~/repo

    steps:

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run: yarn --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn run bootstrap
      - run: yarn run lint

      - run: yarn run test

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "regression/yarn.lock" }}
            - v1-dependencies-

      - run:
          name: regression
          working_directory: regression
          command: |
            yarn --pure-lockfile
            yarn reg

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "regression/yarn.lock" }}

workflows:
  version: 2
  reg_gh_app_pipeline:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages

